### ISSUE TITLE
Use `after` on update for bindings which are deferred together.

### ISSUE THREAD

**Issue by DrSammyD** [mbest/knockout-deferred-updates#26]
I don't know if it's  necessary, nor if it's useful. I just wanted to point out that you could potentially add this functionality to deferred updates, and that I think it would intuitively work in this manner.

Here's a [jsfiddle](http://jsfiddle.net/2uaLxdrk/7/) to illustrate that the second will fire before the first, even though it's marked as `after` the first.

I created this fiddle just to see if it worked in that manner. If you open the debugger, a debugger point will be hit. If you then `Shift + F11` up the stack, before you reach the top, you'll hit another. So both of them are run in the same stack.

Again, likely not an issue for anybody. Just wanted to share this insight into the inner workings of knockout.

**Comment by mbest** [comment]
The `after` flag only controls the order that the bindings initialized. After that, the two bindings are generally updated independently.

**Comment by DrSammyD** [comment]
Indeed. and that makes sense with knockout sans deferred updates as it would be impossible to do when `notifySubscribers` happens synchronously. However your plugin makes it possible, and I just wanted to point that out.

**Comment by mbest** [comment]
No problem. It's an interesting idea.
